language: ruby
before_install:
- gem update --system
- gem install bundler
deploy:
  provider: heroku
  api_key:
    secure: fEJ4h2QKGQKzc7gdM0MB8epWsryx6dNvHY1ZFINXZ/iuaFKyZWjjpCOkiIvZpB2TplpH4rQ5qgS9mt+TzqrZsGjZy9YDvwYTPImbXQZLVqZts6ip53qzJT4XlssBABE95qCyRVzw/H1LPtkzsY1VoIOMOHkiq/3kXaWSpfiewG/ETiwBaHZkQBqx7x6HEJ9Wgw9DU8gNM2OPHzX1m58TtBLo6J1ORpMcBrQXZL/CO2Otf6ExjJZQIi3o5ih7PXcH5+N2oUYX8envaEGZNBjosjf3nK2UEl0V7QLguZ7S7S1Jy32MCPVB/p9IPQittCcXr20/Kk5WxkUIPvfUIx/RYxlIRQCwh0S7Mc3xysMNAgIBD/f9fsA08Y5Kzw7XnFTB2ggdyIViJKpNJvUg10nGrvTlInjg9aTk9Zzg0f6RO5aTkqiqEtgogEW7LAKuEZ7yv3Krkv6Wege7YqLZGtbhcb5LWky+wZ6KIDtCCzlQ4HzxhSJ4JTcEU1RnXFPD2env+H8TkesgcvFoaBEHudbu/3BKX3XpzLsLjucxD155Of9/EwFW7slUzXuNaYD5XUcb3xYMSEnYbFIeFDZX+kwI4Ikr7PFoq1PayjZ6q6C5LbJJZv4nGEgKuBMOj+DumeU1evHxPKWMMjczp+d2wtZ0zlg1Bh0v1yBCv4MaE1DlAUw=
  app:
    master: friend-finder-1808
    production: friend-finder-1808-api
